version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: leandrofidalgo
      POSTGRES_PASSWORD: leo1234
      POSTGRES_DB: mydatabase
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
    container_name: flask-api
    restart: always
    depends_on:
      - postgres
    environment:
      FLASK_APP: app.py
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "3000:3000"

